### ISSUE TITLE
Request for Cygwin Binary

### ISSUE THREAD

**Issue by CMCDragonkai** [benibela/xidel#1]
Since you have a  Win32 binary, perhaps a Cygwin binary?

**Comment by benibela** [comment]
Not sure how that would work, or even what the point is.

Can't you call Windows binaries from Cygwin? And the newest Windows 10 should be abe to run linux binaries directly.

I do not use Windows, it is cross-compiled from linux to win32. 

If you have a cygwin freepascal, you could compile it yourself

**Comment by benibela** [comment]
I think you better to ask Cygwin to package it themselves
