### ISSUE TITLE
Add header + footer in batch script?

### ISSUE THREAD

**Issue by Shohreh** [benibela/xidel#103]
Hello,

Can Xidel add a header and footer, as a smarter way than this?

```
@echo off

SET OUTPUT="joined.gpx"

echo ^<?xml version="1.0" encoding="UTF-8"?^> > %OUTPUT%
echo ^<gpx^>^<trk^>^<trkseg^> >> %OUTPUT%
for %%f in ("*.gpx") do (
xidel.exe "%%f" -se "//trk/trkseg/trkpt" --printed-node-format xml >> %OUTPUT%
)
echo ^</trkseg^>^</trk^>^</gpx^> >> %OUTPUT%
```

Thank you.

**Comment by Reino17** [comment]
Hello Shohreh,

Yes, it can. In addition, I would also suggest you use the integrated [EXPath File Module](http://www.benibela.de/documentation/internettools/xpath-functions.html#modulefile) to directly list, load and parse the local gpx-files within `xidel`.

I didn't know gpx-files, but I assume you mean files like [this one](https://en.wikipedia.org/wiki/GPS_Exchange_Format#Sample_GPX_document).

With ["direct element constructors"](https://www.w3.org/TR/xquery-31/#id-element-constructor):
```
xidel -se "(<gpx><trk><trkseg>{for $file in file:list(.,false(),'*.gpx') return doc($file)//trk/trkseg/trkpt}</trkseg></trk></gpx>)" --output-format=xml --output-node-indent --ignore-namespaces --output-declaration="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
xidel -se ^"^
  (^<gpx^>^<trk^>^<trkseg^>{^
    for $file in file:list(.,false(),'*.gpx') return^
    doc($file)//trk/trkseg/trkpt^
  }^</trkseg^>^</trk^>^</gpx^>)^
" --output-format=xml --output-node-indent --ignore-namespaces^
  --output-declaration="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
```
(if you get `Error Unknown option: output-node-indent`, then please [update](https://sourceforge.net/projects/videlibri/files/Xidel/Xidel%20development/)!)

With ["computed constructors"](https://www.w3.org/TR/xquery-31/#id-computedConstructors):
```
xidel -se "element gpx {element trk {element trkseg {for $file in file:list(.,false(),'*.gpx') return doc($file)//trk/trkseg/trkpt}}}" --output-format=xml --output-node-indent --ignore-namespaces --output-declaration="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
xidel -se ^"^
  element gpx {^
    element trk {^
      element trkseg {^
        for $file in file:list(.,false(),'*.gpx') return^
        doc($file)//trk/trkseg/trkpt^
      }^
    }^
  }^
" --output-format=xml --output-node-indent --ignore-namespaces^
  --output-declaration="<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
```
Without `--output-declaration` your XML-declaration will probably look like one of these two...
```
<?xml version="1.0" encoding="ibm437"?>
<?xml version="1.0" encoding="ibm850"?>
```
...so with the custom XML-declaration you can force it to "UTF-8". This however is only on screen! If you save the output to a file, then `--output-declaration` isn't needed, because the output will always be UTF-8.
```
xidel -se "[...]" --output-format=xml --output-node-indent --ignore-namespaces > joined.gpx
```
Alternatively you can also use `file:write()`:
```
xidel -se "file:write('joined.gpx',element gpx {element trk {element trkseg {for $file in file:list(.,false(),'*.gpx') return doc($file)//trk/trkseg/trkpt}}},{'indent':true(),'omit-xml-declaration':false()})" --ignore-namespaces
xidel -se ^"^
  file:write(^
    'joined.gpx',^
    element gpx {^
      element trk {^
        element trkseg {^
          for $file in file:list(.,false(),'*.gpx') return^
          doc($file)//trk/trkseg/trkpt^
        }^
      }^
    },^
    {'indent':true(),'omit-xml-declaration':false()}^
  )^
" --ignore-namespaces
```
@benibela How about `serialize([...],{QName('x:ignore-namespaces'):true()})` / `file:write([...],[...],{'x:ignore-namespaces':true()})`?

**Comment by Shohreh** [comment]
Thanks very much!

**Comment by Reino17** [comment]
I already mentioned this in my post. Please check the url again.

**Comment by Shohreh** [comment]
Sorry, I only checked [the main site (0.9.8)](downloads), not the [development section on Sourceforge (0.9.9)](https://sourceforge.net/projects/videlibri/files/Xidel/Xidel%20development/).

Is there a way to prevent xidel from displaying the output in the terminal? With big files, it takes a long time.

Also, I find no new file in the directory (output just flies down the screen), and using redirection doesn't work:

```
c:\temp\XML>xidel.join.cmd > test.gpx
An unhandled exception occurred at $00447C9B:
EFOpenError: Unable to open file "c:\temp\XML\test.gpx": The process cannot access the file because it is being used by another process.
  $00447C9B
  $00447B25
  $00422B85  STRLOADFROMFILE,  line 4460 of /home/benito/hg/components/pascal/data/bbutils.pas
  $00422E94  STRLOADFROMFILEUTF8,  line 4520 of /home/benito/hg/components/pascal/data/bbutils.pas
  $0048B825  TXQSTATICCONTEXT__RETRIEVEFROMURI,  line 7066 of /home/benito/hg/components/pascal/data/xquery.pas
  $0048DAFE  TXQEVALUATIONCONTEXT__PARSECACHEDDOCFROMURL,  line 7621 of /home/benito/hg/components/pascal/data/xquery.pas
  $004FE4A7  XQFUNCTIONDOC,  line 3773 of /home/benito/hg/components/pascal/data/xquery__functions.pas
  $0049E9E8  TXQTERMNAMEDFUNCTION__EVALUATE,  line 2795 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $004B7CEC  TXQUERYENGINE__EVALUATESINGLESTEPQUERY,  line 9587 of /home/benito/hg/components/pascal/data/xquery.pas
  $004A1153  TXQTERMPATH__EVALUATE,  line 3247 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $0049B34A  EVALUATEFORLOOP,  line 2326 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $0049D71F  ADDVARIABLEBINDING,  line 2090 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $0049B61D  EVALUATEFORLOOP,  line 2352 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $00499F8B  TXQTERMFLOWER__EVALUATE,  line 2526 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $004A67D4  APPENDCHILDTERMSASCHILDNODES,  line 4464 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $004A637F  TXQTERMCONSTRUCTOR__EVALUATE,  line 4556 of /home/benito/hg/components/pascal/data/xquery_terms.inc
  $004A6729  APPENDCHILDTERMSASCHILDNODES,  line 4459 of /home/benito/hg/components/pascal/data/xquery_terms.inc
```

**Comment by Reino17** [comment]
I highly doubt using `--download` really solved your problem, because `--download` can only be used when either of...
```
xidel --help
[...]
--input=<string>                        Data/URL/File/Stdin(-) to process (--input= prefix can be
                                        omitted)
[...]
  --follow=<string>  or -f              Expression selecting data from the page which will be
                                        followed.
```
...is specified, which is not the case here.

**Comment by Shohreh** [comment]
Indeed, it created a file that only contained… "<empty/>"

Is there no way to save the output into a new file, since "> output.gpx" triggers an error?

`EFOpenError: Unable to open file "c:\XML\test.gpx": The process cannot access the file because it is being used by another process.`

**Comment by Reino17** [comment]
This is probably outside the scope of `xidel`, because, as it says, another process is already claiming access. Close them (or restart your pc if that doesn't help?). Then try again.

**Comment by Shohreh** [comment]
I delete the output file before running the app.

The error only occurs when directing the output to a file, not when run as-is (ie. output to the screen).

If the output can't be saved into a file, what's the point?

**Comment by Shohreh** [comment]
On Windows, in a batch file, I tried the three commands mentioned above. They all fail when redirecting the output to a file instead of the scree.

Just create a couple of GPX files and try to join their points (trkpt) to get a single file:
```
<?xml version="1.0" encoding="UTF-8">
<gpx>
  <trk>
    <trkseg>
      <trkpt lat="44.14225" lon="1.97067">
        <ele>154</ele>
      </trkpt>
      <trkpt lat="44.14225" lon="1.97067">
        <ele>154</ele>
      </trkpt>
    </trkseg>
  </trk>
</gpx>
```

**Comment by benibela** [comment]
If you do `> output.gpx`, it will find output.gpx in `file:list(.,false(),'*.gpx')` and `doc($file)` will try to open it, which it cannot because it is used for output. 

You could do ` `> output.xxx`


>@benibela How about serialize([...],{QName('x:ignore-namespaces'):true()}) / file:write([...],[...],{'x:ignore-namespaces':true()})?

But ignore-namespaces is an input option, not an output option

**Comment by Shohreh** [comment]
Good idea :-)

```
xidel.join.cmd > join.gpx.tmp
mv join.gpx.tmp join.gpx

```
"But ignore-namespaces is an input option, not an output option" : I just copy/pasted the [instructions above](https://github.com/benibela/xidel/issues/103#issuecomment-1566272400).

Thanks!

**Comment by Reino17** [comment]
So, a workflow error in the end. I guess it's all settled now.

@benibela Hah! The documentation really needs a big overhaul!  
At the moment `xidel --help` shows it's a "XPath/XQuery compatibility" option, but a better place would probably be the "Output/Input options". And speaking of which, I'd say split this into "Output options" and "Input options" so there will no more discussion whether something is an input- or an output option.

**Comment by benibela** [comment]
>And speaking of which, I'd say split this into "Output options" and "Input options" so there will no more discussion whether something is an input- or an output option.


But there are also options that are both like `--xml`

**Comment by Reino17** [comment]
Then I'd say specify them twice:
```
Input options:
--xml   ...
Output options:
--xml   ...
```
Or just create 3 categories:
```
Input options:
[...]
Output options:
[...]
Input & Output options:
--xml   ...
```

**Comment by benibela** [comment]
@Reino17 

> Then I'd say specify them twice:
> 
> ```
> Input options:
> --xml   ...
> Output options:
> --xml   ...
> ```

I am not sure if the command line parser can handle that

**Comment by Reino17** [comment]
What do you mean? `--xml` is already an input- *and* output option, which afaik the command-line parser handles just fine. So this just a matter of documentation.

**Comment by benibela** [comment]
@Reino17 

The documentation is automatically generated by the command-line parser
