### ISSUE TITLE
Latest build is not outputing the expression

### ISSUE THREAD

**Issue by mailsanchu** [benibela/xidel#105]
xidel "https://github.com/Netflix/hollow/releases/latest" -e "/html/body/div[4]/div/main/div[2]/div/div[2]/div[1]/div/div[2]"

This command is not printing any result.

Xidel 0.9.9
(20230627.git9905cb0bb10a9c96906cf84b86da7898eeb4c649)
Compiled with FPC3.2.2 x86_64-Linux release C+

https://www.videlibri.de/xidel.html
by Benito van der Zander <benito AT benibela.de>

**Comment by Reino17** [comment]
The node you're querying doesn't exist in the HTML-source of that url, so obviously it'll return nothing.

**Comment by mailsanchu** [comment]
How do i get the latest version from this page https://github.com/Netflix/hollow/releases

**Comment by mailsanchu** [comment]
I am expecting to get this value as of now <a href="/Netflix/hollow/releases/tag/v7.5.9-rc.6" data-view-component="true" class="Link--primary" data-turbo-frame="repo-content-turbo-frame">v7.5.9-rc.5</a>

**Comment by Reino17** [comment]
```
xidel -s "https://github.com/Netflix/hollow/releases" \
      -e '//div[@data-hpc]/section[1]/div/div[2]/div/div/div/div/div/span/a/resolve-uri(@href)'

xidel -s "https://github.com/Netflix/hollow/releases" \
      -e '(//a[@class="Link--primary"])[1]/resolve-uri(@href)'
```
```
xidel -s "https://github.com/Netflix/hollow/releases/latest" \
      -e '$url'

xidel -s "https://github.com/Netflix/hollow/releases/latest" \
      -e '//meta[@property="og:url"]/resolve-uri(@content)'

xidel -s "https://github.com/Netflix/hollow/releases/latest" \
      -e '//ol/li[2]/a/resolve-uri(@href)'
```
Better yet... use the API:
```
xidel -s "https://api.github.com/repos/Netflix/hollow/releases" \
      -e '$json(1)/html_url'

xidel -s "https://api.github.com/repos/Netflix/hollow/releases/latest" \
      -e '$json/html_url'
```
Relevant SO posts:  
- [Bash script to download latest release from GitHub](https://stackoverflow.com/a/73007866)  
- [I want to use wget with variable](https://stackoverflow.com/a/73756890)

P.s. Since you're on Linux, please use single-quotes --> `-e 'function("string")'`.

**Comment by mailsanchu** [comment]
The above works. Will it not work if I copy the full xpath from chrome?

**Comment by mailsanchu** [comment]
`/html/body/div[1]/div[6]/div/main/turbo-frame/div/div/div/div/div[1]/div[1]/div[1]/div[1]/h1` is the one I copied from chrome

**Comment by benibela** [comment]
Chrome runs javascript that changes the page. You would need to disable javascript there to get a usable xpath

**Comment by mailsanchu** [comment]
I need to run 0.9.8 and see if it works. It used to work before.

**Comment by Reino17** [comment]
Without javascript `xidel` renders the Github page differently. Use the following command to see how (with proper indentation):
```
xidel -s "https://github.com/Netflix/hollow/releases" -e . --output-node-format=xml --output-node-indent
```
For `xidel` that would be:
```
xidel -s "https://github.com/Netflix/hollow/releases" -e '
  path(//div[@data-hpc]/section[1]/h2) ! replace(.,"Q\{\}","")
'
/html[1]/body[1]/div[1]/div[4]/div[1]/main[1]/turbo-frame[1]/div[1]/div[1]/div[3]/section[1]/h2[1]
```
Or a little bit simplified:
```
xidel -s "https://github.com/Netflix/hollow/releases" -e '
  /html/body/div[1]/div[4]/div/main/turbo-frame/div/div/div[3]/section[1]/h2
'
v7.5.9-rc.5
```

**Comment by mailsanchu** [comment]
It must be github change and my version upgrade just a coincidence. I am happy to close this ticket
