### ISSUE TITLE
[XPath] How to get both items?

### ISSUE THREAD

**Issue by Shohreh** [benibela/xidel#106]
Hello,

I'm using Xidel for this, but it's actually an XPath question… that I don't where to ask.

I need to grab "FOO" and "BAR" from this div:
```
<div class="panel-heading collapsed" role="tab">
  <div class="col-xs-1 h_class">
    <label class="label label-warning">FOO</label>
  </div>
  <div class="col-xs-9 name_station">
    BAR
  </div>
</div>
```

The following works to get FOO, but I haven't found how to get BAR. Anybody knows?

`xidel.exe -se "//div[@class='panel-heading collapsed']/div/label/text()" test.html`

Thank you.

PS: If you know of a good site/book to learn XPath, I'm interested

**Comment by Reino17** [comment]
Create a sequence:
```
xidel -s test.html -e "//div[@class='panel-heading collapsed']/(div/label,div[2])"
FOO

    BAR

```
"BAR" stripped of white-space:
```
xidel -s test.html -e "//div[@class='panel-heading collapsed'] ! (div/label,normalize-space(div[2]))"
FOO
BAR

xidel -s test.html -e ^"^
  //div[@class='panel-heading collapsed'] ! (^
    div/label,^
    normalize-space(div[2])^
  )^
"
FOO
BAR
```
> _but it's actually an XPath question… that I don't where to ask._

I think the [forums](https://sourceforge.net/p/xidel/discussion/), the [mailing list](https://sourceforge.net/p/videlibri/mailman/videlibri-xidel/), or [StackOverflow](https://stackoverflow.com/questions/tagged/xidel) would be a better place to ask.

> _PS: If you know of a good site/book to learn XPath, I'm interested_

https://github.com/benibela/xidel/issues/67#issuecomment-770084663

And some general XPath/XQuery urls:
- https://www.w3.org/TR/xquery-31/
- https://www.w3.org/TR/xpath-31/
- https://www.w3.org/TR/xpath-functions-31/
- http://www.xqueryfunctions.com/xq/
- https://docs.basex.org/wiki/Getting_Started (urls beneath "XML and XQuery")
- https://en.wikibooks.org/wiki/XQuery
- http://www.datypic.com/books/xquery/
- https://xquery.forhumanists.org/

**Comment by Shohreh** [comment]
Thanks!
