### ISSUE TITLE
HTTPS sites do not work with an HTTPS proxy

### ISSUE THREAD

**Issue by neilmcguigan** [benibela/xidel#11]
I have a proxy with trustedproxies.com . HTTPS sites work fine with this proxy when using curl, wget, or Apache HTTP Components. 

Xidel works fine using the same proxy over HTTP

Reproduction:

xidel --proxy='ip:port' https://example.com -e //title

and it waits a while then...

**** Retrieving:https://example.com ****
An unhandled exception occurred at $0010757D :
EInternetException : Connecting failed
when talking to: https://example.com/
  $0010757D
  $00107C38
  $00026C5D
  $00026AD8
  $000271D5
  $000253E6
  $0002508E
  $00011834
  $0003AF28
  $0003ABE0
  $0003C741
  $0004028E
  $0004E60D

The above is from Xidel 0.8, but 0.9.6 has the same issue

**Comment by benibela** [comment]
I tried it with a proxy from [this list](https://www.sslproxies.org/)   (138.201.63.123:31288) and it worked. Perhaps it uses an ssl/tls version that is not enabled in the Internet Explorer config.
