### ISSUE TITLE
Adding HTTP(S) headers not working

### ISSUE THREAD

**Issue by smartmic** [benibela/xidel#112]
The `--header` (or `-H`) option does not work for me for GET requests. What am I doing wrong here:

```
$ # adding custom header 'Cookie' is not part of request header ⇒
$ xidel https://httpbin.org/headers -H "Cookie: a=b" -e "$json?*"
{
  "Accept": "text/html,application/xhtml+xml,application/xml,text/*,*/*",
  "Host": "httpbin.org",
  "User-Agent": "Mozilla/5.0 (compatible; Xidel)",
  "X-Amzn-Trace-Id": "…"
}
$ # same with curl works ⇒
$ curl https://httpbin.org/headers --header "Cookie: a=b" 
{
  "headers": {
    "Accept": "*/*", 
    "Cookie": "a=b", 
    "Host": "httpbin.org", 
    "User-Agent": "curl/8.8.0", 
    "X-Amzn-Trace-Id": "…"
  }
}
```

**Comment by Reino17** [comment]
You have to put `--header` / `-H` in front of the url.

Even `curl` dictates this (`Usage: curl [options...] <url>`), but apparently it is more forgiving than `xidel`.

**Comment by smartmic** [comment]
Oh yes, thanks! I was too easily led astray as the `--help' page did not distinguish between the `--extract' and `--follow' options (which are usually after the url in the examples) and all other options.  Maybe a short update in the help page or adding a command synopsis would help (I still hope such a great tool will be maintained and get an update sometime in the future).
