### ISSUE TITLE
Using xidel - linux x32 on Openwrt x86 (virtual box)? "No such file or directory"

### ISSUE THREAD

**Issue by Baltazar500** [benibela/xidel#114]
Hi. 

I'm trying to use xidel - linux x32 on OpenWRT x86 (virtual box), but I get a "No such file or directory" error when running the binary. What's the problem?

```
-bash-4.3# strace "/tmp/bin/xidel"
execve("/tmp/bin/xidel", ["/tmp/bin/xidel"], [/* 14 vars */]) = -1 ENOENT (No such file or directory)
brk(0x8cfd000)                          = 0x8cfd000
write(2, "strace: exec: No such file or di"..., 40strace: exec: No such file or directory
) = 40
exit_group(1)                           = ?
+++ exited with 1 +++
```

**Comment by benibela** [comment]
It needs a dynamic loader

e.g. the 64-bit version needs:

    $ readelf -l  xidel  |  grep interpreter
         [Requesting program interpreter: /lib64/ld-linux-x86-64.so.2]
    $ strings | grep ld-linux
         /lib64/ld-linux-x86-64.so.2

Different Linux versions have a different name for that file

**Comment by Baltazar500** [comment]
>It needs a dynamic loader

 Thanks for the tip

In xidel x32 this is ld-linux.so.2 I found the necessary interpreter on OpenWRT and created a symlink /lib/libc.so -> /lib/ld-linux.so.2, which allowed me to run xidel. After installing libopenssl, https support started working. The issue is resolved.

**Comment by benibela** [comment]
>In xidel x32 this is ld-linux.so.2 I found the necessary interpreter on OpenWRT and created a symlink /lib/libc.so -> /lib/ld-linux.so.2, 

good, if that solves it

i would have thought the name always starts with "ld- something" not libc

**Comment by Baltazar500** [comment]
In addition to my last message: 

To support https you need to add symlinks

```
ln -s /usr/lib/libssl.so.3 /usr/lib/libssl.so
ln -s /usr/lib/libcrypto.so.3 /usr/lib/libcrypto.so
```
