### ISSUE TITLE
Pull more of the documentation from http://videlibri.sourceforge.net/xidel.html to here

### ISSUE THREAD

**Issue by paul-hammant** [benibela/xidel#12]
I think this is the same project. One doesn't link to the other but it is the same.

Github has a great WIKI, which would be perfect, IMO

**Comment by benibela** [comment]
I could write a script to copy all documentation in the wiki.

But if then someone else edits the wiki, it could hardly copy it back and it becomes desynchronized

**Comment by benibela** [comment]
made a wiki page: https://github.com/benibela/xidel/wiki/Frequently-asked-questions
