### ISSUE TITLE
new --delete feature

### ISSUE THREAD

**Issue by paul-hammant** [benibela/xidel#13]
Like --extract, but the opposite.

```
<div>
    <span>I want to keep this</span>
    <div class="I_want_to_delete_this">
        <span>blah< blah/span>
    </div>
    <span>I want to keep this too</span>
</div>
```
With `--delete "//div[@class='I_want_to_delete_this']"` I would expect to end up with:

```
<div>
    <span>I want to keep this</span>
    <span>I want to keep this too</span>
</div>
```

**Comment by benibela** [comment]
This has the conceptual problem  that all data is immutable. 
So it could not actually delete it from the existing document.

You can use the transform function

     xidel xx.xml --xml -e 'let $delete := //div[@class="I_want_to_delete_this"] return transform(/, function($e){ if ($delete[$e is .]) then () else $e})' 

or

    xidel /tmp/xx.xml --xml -e 'let $delete := //div[@class="I_want_to_delete_this"] return transform(/, function($e){ $e[not($delete[$e is .])]})'

**Comment by paul-hammant** [comment]
I guess. And maybe the snippet you have above is perfect for copy/pasting into the documentation "H1 Effective deletion of nodes"
