### ISSUE TITLE
xidel in homebrew

### ISSUE THREAD

**Issue by paul-hammant** [benibela/xidel#14]
Mac's homebrew package manager has a simple ruby DSL for installation of bits and pieces.

Here's one for `ack` that is relatively simple - https://github.com/Homebrew/homebrew-core/blob/master/Formula/ack.rb

**Comment by benibela** [comment]
In the meantime Michael Klement has update the mac-build instructions: https://www.evernote.com/shard/s69/sh/ff1e78f3-a369-4855-b18f-6184ce789c45/f3511927d0fb356ce883835f2eb712e0

**Comment by benibela** [comment]
First attempt: https://github.com/Homebrew/homebrew-core/pull/27149

**Comment by paul-hammant** [comment]
I can confirm this works for me:

```
brew install https://raw.githubusercontent.com/benibela/homebrew-core/d6dedb62d78832db389ec1fe0903f2b509ebe1cc/Formula/xidel.rb
```

yields a functioning xidel.

**Comment by benibela** [comment]
It is done. The final issue can be closed
