### ISSUE TITLE
Not working if CSS class contains underscores

### ISSUE THREAD

**Issue by rhazor** [benibela/xidel#16]
E.g. scrape movie description from IMDb:
`-e 'div.plot_summary div.summary_text'` gives:

```
Error:
err:XPST0003: Need whitespace after operator
in: div.plot_summary div [<- error occurs before here] .summary_text
```

Also any hint how to select non-HTML tags like `itemprop="description"` used in IMDb site?

**Comment by Reino17** [comment]
`-e "//div[@class='summary_text']"`, or `-e "<div class='summary_text'>{.}</div>"`.

**Comment by rhazor** [comment]
Yeah I solved it with` -e "css('#title-overview-widget div[itemprop=description]')"`
