### ISSUE TITLE
Is there some mechanism to decode HTML charset

### ISSUE THREAD

**Issue by cybexr** [benibela/xidel#20]
Symptom : xidel cannot treat charset correctly.
Example:  xidel.exe --html 5.htm -e "//div[@class='qxName']/a" --stdin-encoding=oem >5o.htm --output-encoding=input

This 5.htm has <meta http-equiv="Content-Type" content="text/html; charset=gb2312" />, but the outpupt is incorrect. 

After I convert the 5.htm file to UTF8 encoded, the output is fine. It seems xidel always treat input file as UTF8 , am I missed something? or xidel can only work like this .

**Comment by benibela** [comment]
What are the encodings of the files? 

With `-output-encoding=input` 5o.htm should have the same encoding as 5.htm

`--stdin-encoding=oem ` is ignored here, it is only used when you do `- <5.htm`

**Comment by cybexr** [comment]
the 5.htm file is GBK encoded, which is DBCS. it's quite different from european-language( all are SBCS)  https://en.wikipedia.org/wiki/GBK_(character_encoding)
https://en.wikipedia.org/wiki/DBCS

actually the 5.htm is download from a web-site http-response with header:Content-Type: text/html; charset=gb2312 .

**Comment by cybexr** [comment]
tryed again, just with option : -output-encoding=input  result is correct.  both on windows&centos. 
maybe I'm confused with debugging so much http response yesterday. 
Thank you benibela !
