### ISSUE TITLE
problem with regex & match-contains

### ISSUE THREAD

**Issue by cybexr** [benibela/xidel#21]
xidel 2.htm --output-encoding=input -e "<head><script><t:match-text contains="mapInfo"/><template:read source="text()" var="regex" regex='[1-9]\d*\.\d*|0\.\d*[1-9]\d*'/></script></head>"
**** Retrieving: 2.htm ****
**** Processing: 2.htm ****
Error:
Matching of template <unknown> failed. for an unknown reason

The 2.htm contains javascript like this:
    <script type="text/javascript" language="javascript">
        var mapInfo={zoom:15,mapZoom:15,px:"113.9609603881836",py:"22.5539608001709",isKey:"1"};

**Comment by cybexr** [comment]
something weired happed, see following 2 commands. Is there some difference between {$} and <template:read>  ??

**>xidel 3.htm --output-encoding=input -e "<head><script>{$jssrc := .}</script></head>"**
**** Retrieving: 3.htm ****
**** Processing: 3.htm ****
** Current variable state: **
jssrc :=  var mapInfo={zoom:15,mapZoom:15,px:"113.9609603881836",py:"22.5539608001709",isKey:"1"};
... bla bla ...

**>xidel 3.htm --output-encoding=input -e "<head><script> <template:read source="text()" var="jscc"/> </script></head>"**
**** Retrieving: 3.htm ****
**** Processing: 3.htm ****
Error:
Matching of template <unknown> failed. for an unknown reason

Partial matches:

**Comment by benibela** [comment]
It is the quotes

` "<script> <template:read source="text()" var="` are three parameters like ` "<script> <template:read source="`,          `text()` and  ` " var="` like `  "<script> <template:read source=text() var="`

**Comment by cybexr** [comment]
put template into t3.htm, still match error

t3.htm` <head><script><template:read source="text()" var="jscc"/></script></head>`

**>xidel 3.htm --extract-file=t3.htm**
```
**** Retrieving: 3.htm ****
**** Processing: 3.htm ****
Error:
Matching of template <unknown> failed. for an unknown reason

Partial matches:
<html xmlns="http://www.w3.org/1999/xhtml">

 <head>

  <title>
   D??￥?ì?ê?éò3μ?í?
   </title>

  <script type="text/javascript"                   <---- <script>
  language="javascript">
                                                          <template:read source="text()" var="jscc"/>
                                                          </script>
                                                         </head>
                                                         </>
<!--template end-->

   var
   mapInfo={zoom:15,mapZoom:15,px:"113.96096038818
   36",py:"22.5539608001709",isKey:"1"};
```

...

**Comment by benibela** [comment]
Oh, then it is the script. HTML can only have text in a script

There is an option for that `--extract-kind xml-pattern`

**Comment by cybexr** [comment]
Working perfectly now. Thank you benibela .

And the  option: xml-pattern doesn't exists in the readme doc. Is there some more specific document about this great tool?  What I've got is:

- http://www.videlibri.de/xidel.html 
- http://www.videlibri.de/xidel_readme.txt 
- http://www.benibela.de/documentation/internettools/extendedhtmlparser.THtmlTemplateParser.html
- and extendedhtmlparser_tests.pas  in Internettools-repo is helpful too.

Is there some document I missed? And IMHO, the document is still poor, can't show how powerful this framework is, and is not friendly to newbie.

**Comment by benibela** [comment]
I forgot to mention it.

There is 

* XQuery standard: https://www.w3.org/TR/xquery-30/

* Function list: http://www.benibela.de/documentation/internettools/xpath-functions.html

I am too slow at writing documentation. Sometimes thinking an hour about a single sentence...

**Comment by cybexr** [comment]
got it . thank you again for your response & your great framework!
