### ISSUE TITLE
template:optional="true" with null output feature ?

### ISSUE THREAD

**Issue by cybexr** [benibela/xidel#24]
The sample template :

``
    <div class="list rel">
        <dl class="plotListwrap clearfix">
            <dd>
...
            </dd>
        </dl>
        <div class="listRiconwrap">
            <p template:optional="true" class="priceAverage">
                <span>{$price := .}</span>
            </p>
            <p template:optional="true" class="ratio">
                <span>{$ratio:= .}</span>
            </p>
        </div>        
    </div>+
  ``  
within the outer loop, if  ``<p template:optional="true" class="priceAverage">`` exists, everything ok.  if not exists, the result output will miss one element.  

Is there some xidel-attr can control: if not exist then output as null ?

**Comment by benibela** [comment]
There is no flag for that

You could do it without matching with xpath:

    <div class="listRiconwrap">
       {$price := .//p[@class="priceAverage"]//span,
        $ratio := .//p[@class="ratio"]//span}
    </div>

Or use an object to set a default value

    <div class="listRiconwrap">
      {$obj := {"price": null, "ratio": null }}
      <p template:optional="true" class="priceAverage"> <span>{$obj("price") := .}</span> </p> 
      <p template:optional="true" class="ratio"> <span>{$obj("price"):= .}</span> </p> 
    </div>

**Comment by cybexr** [comment]
Got it,  benibela thank you!
