### ISSUE TITLE
Extract correct item from HTML when page contains identical classes

### ISSUE THREAD

**Issue by rhazor** [benibela/xidel#25]
E.g. HTML structure:

```
<div class="parent">
      <a class="item">Item 1</a>
      <a class="item">Item 2</a>
</div>

<div class="parent">
      <h4 class="unique-identifier">Extract what's under:</h4>
      <a class="item">Item 3</a>
      <a class="item">Item 4</a>
</div>
```

As you can see HTML has identical parent items all over, but only one parent item has h4 tag inside, which can be somehow used as unique identifier? So that only items under that parent would be extracted Item 3 and Item 4.

If I run -e  'div.parent a' it extracts all items from all parents, but we want only items from within the parent that also has h4 child.

Also why if you add class to 'a' element, it doesn't extract? E.g.  -e  'div.parent a.item' doesn't work.

**Comment by Reino17** [comment]
```
$ cat <<EOF | xidel -s - -e '//div[@class="parent"][h4]/a'
> <div class="parent">
>       <a class="item">Item 1</a>
>       <a class="item">Item 2</a>
> </div>
>
> <div class="parent">
>       <h4 class="unique-identifier">Extract what's under:</h4>
>       <a class="item">Item 3</a>
>       <a class="item">Item 4</a>
> </div>
> EOF
Item 3
Item 4
```
Is this what you're looking for?

**Comment by rhazor** [comment]
It works from static .html, but not working from the URL I'm trying. E.g. extract genres (not under title, but scroll down under Storyline, Taglines, etc.) from https://www.imdb.com/title/tt4779682/ The 'Genres: Action | Horror | Sci-Fi | Thriller'.

The parent div has 'see-more inline canwrap' as classes and there are other parents that has same classes, but needs to be ignored, so I thought use that h4 tag as unique identifier, but I did more browsing turns out some other parents also has a h4 child.

Any ideas how to extract 'Action | Horror | Sci-Fi | Thriller' part (minus the '|' item, I use '--output-separator=", " for separator. That one at the bottom or the one at the top under title (subtext class)? Which one is more approachable?

**Comment by rhazor** [comment]
Why  --output-separator=", " doesn't work? From `Action Horror Sci-Fi Thriller` to `Action, Horror, Sci-Fi, Thriller`, tried on both examples.

**Comment by rhazor** [comment]
Doesn't work if json contains only one item e.g. https://www.imdb.com/title/tt6859352/ 'Comedy'

**Comment by Reino17** [comment]
So the value of the object _genre_ is either a string when there's only 1 genre specified, or an array when there are multiple. This is what I probably would've done:
```
-e "json(
      //script[@type='application/ld+json']
    )/(
      if (genre instance of array()) then
        join(
          (genre)()
          ,', '
        )
      else
        genre
      )"
```
You can also turn the if-statement around:
```
-e "json(
      //script[@type='application/ld+json']
    )/(
      if (genre instance of string) then
        genre
      else
        join(
          (genre)()
          ,', '
        )
      )"
```
Please have a look at the following urls to learn more about Xidel and XPath/XQuery:
http://videlibri.sourceforge.net/xidel.html#examples
http://www.benibela.de/documentation/internettools/xpath-functions.html
http://www.xqueryfunctions.com/xq/
https://www.w3.org/TR/xpath-functions-30/

**Comment by rhazor** [comment]
Hey thanks for the links, but I had to smash it all into one line in order to make it work in batch script. Maybe I just don't know how to wrap it up correctly.

**Comment by Reino17** [comment]
You can have a look at my [hobby-project](https://github.com/Reino17/BatchGemist) to see Xidel being used in batch, as well as how to use 'prettified' Xidel-queries in batch.
