### ISSUE TITLE
Unknown namespace prefix: jnlib

### ISSUE THREAD

**Issue by Reino17** [benibela/xidel#28]
[http://www.benibela.de/documentation/internettools/xpath-functions.html#modulejnlib](http://www.benibela.de/documentation/internettools/xpath-functions.html#modulejnlib):
> In the Pascal Internet Tools library the unit xquery_json.pas needs to be loaded, before these functions are available.

Did you include this library in the binaries you supply, Benito? No matter what function I try, I constantly get `Unknown namespace prefix: jnlib`.

**Comment by Reino17** [comment]
Ah, I see.<br>
I was looking at https://stackoverflow.com/q/54552141. Initially I had...
```
$ cat <<EOF | xidel -s - -e 'for $x in $json/conditional_ks return [$x() ! $x(.)()]'
{
  "conditional_ks": {
    "saturday": ["reportdata_by_type"],
    "sunday": ["rt_report", "metadata"]
  }
}
EOF
```
...return `["reportdata_by_type", "rt_report", "metadata"]`, but now I understand...
```
$ cat <<EOF | xidel -s - --xmlns:jnlib="http://jsoniq.org/function-library" -e '$json/[jnlib:values(conditional_ks)()]'
{
  "conditional_ks": {
    "saturday": ["reportdata_by_type"],
    "sunday": ["rt_report", "metadata"]
  }
}
EOF
```
...does the same.

I did a quick reading on XQuery 3.1. I understand it includes lots of json functions. Now I'm curious; how would this query look like when using XQuery 3.1?

**Comment by benibela** [comment]
`?*` gives on level of values, so

```
cat <<EOF | xidel -s - -e 'array{$json?*?*?*}'
{
  "conditional_ks": {
    "saturday": ["reportdata_by_type"],
    "sunday": ["rt_report", "metadata"]
  }
}
EOF

```

**Comment by Reino17** [comment]
Thank you.
