### ISSUE TITLE
can't run on rasperry pi2 (armhf)

### ISSUE THREAD

**Issue by masavini** [benibela/xidel#31]
hi,
i downloaded and extracted the binary from xidel-0.9.6.linuxarm.tar.gz
when i run it, however, i get:
```
$ ls -l
-rwxr-xr-x 1 teo teo 6603687 Jan  8  2017 xidel
$ ./xidel --version
-bash: ./xidel: No such file or directory
```

what am i missing?

**Comment by benibela** [comment]
That is an old version. You better use 0.9.8 or 0.9.9 ("nightly")

Perhaps it is looking for a wrong ELF interpreter.   `readelf -l xidel | grep interpre` shows the one xidel needs. Check if you have it.

**Comment by masavini** [comment]
thanks for your reply.

i've just realized i forgot to mention i'm running ubuntu server 18.04.

there is no linuxarm download for 0.9.8 version, so i ran the command you suggested using the 0.9.6 linuxarm version:
```
$ readelf -l xidel | grep interpre
      [Requesting program interpreter: /lib/ld-linux.so.3]
```

since there is no such a file in ubuntu 18.04 armhf, i ran:
```
$ sudo ln -s /lib/ld-linux-armhf.so.3 /lib/ld-linux.so.3
```
... and now it is working!
```
$ ./xidel
Xidel XQuery/XPath/CSS/JSONiq engine and webscraper
Use --help for a list of available command line parameters.
Or --usage for the usage information of the readme.
```
