### ISSUE TITLE
Intermittent file open errors

### ISSUE THREAD

**Issue by oleliabo** [benibela/xidel#32]
Thanks for this great tool, running multiple xidel instances at the same time (operating on the same set of files) as part of a system test, we sometimes get the error:
```
$ xidel -s --xpath3 "/*" XXX
An unhandled exception occurred at $000000000047DF55:
EFOpenError: Unable to open file "XXX"
  $000000000047DF55
  $000000000047DD54
  $000000000045E9E2
```
Could the problem be that the files are not opened in READ ONLY mode?

**Comment by benibela** [comment]
It is opened read only, but it is also locked during reading. 

I do not set a locking mode, so it uses the  default locking flags of FreePascal, which appears to be `LOCK_EX or LOCK_NB`

**Comment by oleliabo** [comment]
Ok, this would explain what Im seeing. My preference would be to remove the locking so that many processes can operate on the same input file at the same time.

**Comment by benibela** [comment]
changed in 5ce0b79e39040c6edc2f142072a46ef3776ee521
