### ISSUE TITLE
[Feature request] --download param

### ISSUE THREAD

**Issue by MatrixView** [benibela/xidel#38]
Hi Benito,

Could you make it so that when using --download without a given '=filename.ext', uses the content-disposition value of the header as the filename to the current folder? If the file already exists in the filesystem return error for that.

$headers example: 

    Content-Disposition: attachment; filename="the-meant-filename.zip"; filename*=UTF-8''the-meant-filename.zip

Or use some special char for that...
ie.  in combo with a given foldername, and also overwrite if file exists...

    --download "foldername\*"

and/or... do you already have a smart workaround (for the time being)?  :-)

Many thanx!

**Comment by Reino17** [comment]
Is the url for this file still available and can you share it?

**Comment by benibela** [comment]
I could add it. But I am not sure if it is a good idea  to allow the server to choose the file name for the download considering security issues. (although the server can choose it already with a redirection)

You could do it like

    --download '{extract($headers[starts-with(., "Content-Disposition")], "filename=""(.*?)""", 1)}'

And the download overrides existing files

**Comment by MatrixView** [comment]
@Reino17 @benibela Thanx for helping me out. I've used Aria2 for the file download in the meantime as it automatically uses the Content-Disposition value. (Xidel off course for extraction of the download-links, then pipe it to Aria2)
