### ISSUE TITLE
can i use xquery flwor with xidel?

### ISSUE THREAD

**Issue by zpimp** [benibela/xidel#39]
i tried something simple but i dont know how to read the file, this doesnt work

for $a in doc("books.xml")//author
order by $a/last, $a/first
return $a/last

**Comment by Reino17** [comment]
*http://www.benibela.de/documentation/internettools/xpath-functions.html#fn-doc:*
> `fn:doc($uri as xs:string?) as document-node()?`  
Retrieves a document using a **URI** supplied as an `xs:string`, and returns the corresponding document node. See the XPath/XQuery [function reference](https://www.w3.org/TR/xpath-functions-30/#func-doc).

If you want to open a local file, then...
```
xidel -s "books.xml" --xquery '
  for $a in //author
  order by $a/last,$a/first
  return $a/last
'
```
...to let Xidel open the file directly is the first thing to do.

If you really want to open the file "in-query", then `parse-xml(file:read-text("books.xml"))` would do.

**Comment by zpimp** [comment]
`xidel -s "wg" --xquery '
  for $d in //tbody
  return count($d/tr) $d
'
`
how can i return 2 items , and the xpath of $d

what im trying to do is loop through all the stuff in the html and create a csv with the important data
ive done some scraping, and i want to make a generic scraper

**Comment by Reino17** [comment]
What is `"wg"`? Is the html-source of https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal) ?

> what im trying to do is loop through all the stuff in the html and create a csv with the important data

That's not what your latest query is doing. I'm having a hard time trying to figure out what output you're actually looking for. Please explain.

**Comment by zpimp** [comment]
```
$ time ./xidel -s "wg" --xquery '
   for $d in //*                                return(
if (count($d/*)>30) then $d/replace(path(), "Q[{][^}]*[}]", "")
else ())'                                       /html[1]/body[1]/div[1]/div[1]/main[1]/div[3]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[1]/table[1]/tbody[1]
/html[1]/body[1]/div[1]/div[1]/main[1]/div[3]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[2]/table[1]/tbody[1]                              /html[1]/body[1]/div[1]/div[1]/main[1]/div[3]/div[1]/div[1]/div[2]/table[1]/tbody[1]/tr[2]/td[3]/table[1]/tbody[1]
                                                real    0m0.529s
user    0m0.350s                                sys     0m0.040s
```
yes that is the url and this is the output i need, the nodes wich contain other nodes

its just a step for how i thought i can get a csv from html

how would you suggest to convert html to csv? is there a more simple way?

**Comment by Reino17** [comment]
Since you're still not clear on what you're actually after, I'm going to assume you want to turn the 3 tables on that wiki-page into a CSV list, like:
```
1,United States,21.439.453
-,European Union,18.705.132
2,China,14.140.163
[...]
```
This website is not simple! There are of course multiple ways to accomplish this, but this is how I would do it.

I would start off by focusing on the `<table class="wikitable sortable" [...]>` node that holds the 3 tables.  
Next, all the information you need is in the 3<sup>rd</sup> `<tr>` node and onward, so that would mean `//table[@class="wikitable sortable"]//tr[position() > 2]` so far.

```
-e '//table[@class="wikitable sortable"]//tr[position() > 2]/td[1]'
1
-
2
3
4
5
[...]
192
```
The index (the 1<sup>st</sup> `td` node) looks okay.
```
-e '//table[@class="wikitable sortable"]//tr[position() > 2]/td[2]//a[@title]'
United States
European Union
China
Japan
Germany
[...]
Tuvalu
```
The country names look okay too.  
*(`(td[2]//text())[2]`, or in other words the 2<sup>nd</sup> text-node of the 2<sup>nd</sup> `td` node, would work too)*
```
-e '//table[@class="wikitable sortable"]//tr[position() > 2]/td[3]'
21,439,453

18,705,132

14,140,163

5,154,475

3,863,344

[...]

38

```
The GDP values don't look okay yet. The new line needs to be removed for every value and in addition I would replace the commas with dots to prevent confusing in a CSV list.
```
-e '//table[@class="wikitable sortable"]//tr[position() > 2]/replace(replace(td[3],"\r\n?|\n",""),",",".")'
21.439.453
18.705.132
14.140.163
5.154.475
3.863.344
[...]
38
```
*(`x:lines(td[3])[1]` would work too to remove the new lines. `x:lines()` is a shorthand for `tokenize(.,"\r\n?|\n")`)*

The final step is to join all values together separated by a comma:
```
xidel -s "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)" -e '
  //table[@class="wikitable sortable"]//tr[position() > 2]/join(
    (
      td[1],
      td[2]//a[@title],
      replace(
        replace(td[3],"\r\n?|\n",""),
        ",","."
      )
    ),
    ","
  )
'
1,United States,21.439.453
-,European Union,18.705.132
2,China,14.140.163
3,Japan,5.154.475
4,Germany,3.863.344
5,India,2.935.570
[...]
192,Tuvalu,38
```

**Comment by zpimp** [comment]
you are right, im trying to get those tables into csv's
but i dont want to make a specific scraper for this page, i want to make a generic scraper, and this page was for testing

my idea is that relevant data in a page is normally in a form o subnodes to a key node (or 3 in this case) its either td's in a table or div's in some other node

there was a website that i saw do this scraper.io not sure, cant find it right now, it didnt get all data and was limited but thats where i got my idea from

 this is not fit-all solution there are other cases
and some data resides in attributes, not nodes, and right now i can get xpaths of subnodes only, but not xpaths of their attributes

i hope i was able to explain in more detail what i want, i realise its a bit more work, but i think its doable

**Comment by Reino17** [comment]
> i want to make a generic scraper

Impossible if you ask me. Every websites is different.
> `real	0m55.978s`

Such an approach is really inefficient!

**Comment by zpimp** [comment]
in the end it comes down to aligning a csv , cause missing a node offsets the data
im not trying to make it completely automatic, there would be some input needed,  for example there is lot of unneeded crap like classes and ids, these columns have to be selected for elimination manually
