### ISSUE TITLE
Please release binaries also on github

### ISSUE THREAD

**Issue by noisy** [benibela/xidel#4]
each release listed https://github.com/benibela/xidel/releases should contain binaries available to download. Places like sourceforge are not very stable lately...

**Comment by benibela** [comment]
That seems hard to integrate in my workflow

* I only create the tags after uploading all the binaries.  (so the tag points to the commit where the webpage is updated with the download links )

* It is all automated  and uploads using rsync. Does not seem as if github accepts rsync uploads (Xidel could probably upload itself, buring the cross compilation, I do not have a Xidel that runs on my platform)

* Sourceforge was sold recently. It might get more stable now

**Comment by benibela** [comment]
Turns out I am making these releases much less frequently than I had planed, so I can just upload the binaries here on the webpage manually, too. Still it would be much better if github had rsync support for automated release uploading like sourceforge
