### ISSUE TITLE
fetching data is very slow

### ISSUE THREAD

**Issue by danielb2** [benibela/xidel#42]
Hi, I compared fetching the same data with `xidel` vs `curl | xidel -` and the difference is significant.

<img width="701" alt="fish__Users_daniel" src="https://user-images.githubusercontent.com/26678/70834168-828cc500-1dae-11ea-977d-71efa1af6e9f.png">

( Btw, is there a way to supress the fetching and processing ? it's weird it's piped to stderr since it's not an error )

**Comment by benibela** [comment]
I do not experience that:

![image](https://user-images.githubusercontent.com/1205129/70837495-29e81700-1e04-11ea-9322-223e5dd04431.png)

which os and xidel version?

**Comment by danielb2** [comment]
oops, I should have given that.

Xidel 0.9.8
macOS Mojave (10.14.3)

**Comment by benibela** [comment]
I do not know what happens on a Mac...

Perhaps there is a profiler to see where it spends the time?

Is there a difference between http and https downloads?
>( Btw, is there a way to supress the fetching and processing ? it's weird it's piped to stderr since it's not an error )

With the `-s` option

**Comment by danielb2** [comment]
Is there any particular http site you'd like me to try? I tried to find something without luck.

I don't know about a profiler

**Comment by benibela** [comment]
Are you sure it is 0.9.8? I do not have that version for mac

Apple has a tool called Instruments for profiling

Or  calling xidel with prepending `strace -c` or `ltrace -c` can give some information

**Comment by benibela** [comment]
no feedback
