### ISSUE TITLE
map:merge() returns duplicate keys

### ISSUE THREAD

**Issue by Reino17** [benibela/xidel#43]
```
echo '{"a":1,"b":2,"c":3}' | xidel -s - -e 'map:merge(($json,{"c":4}),{"duplicates":"use-last"})'
{
  "a": 1,
  "b": 2,
  "c": 3,
  "c": 4
}
```
Bug? I know development of XQuery 3.1 functions is still in progress, but this shouldn't happen.

**Comment by benibela** [comment]
I know that this can happen.

Right now the maps are just a list of key/value pairs. It needs a new 
map type to check efficiently if there are duplicate keys

**Comment by benibela** [comment]
Now there is a new map type. Not an XPath 3.1 map type, but a faster implementation of the current map.

But I have not tested it enough to use it with map:merge. So now there is a new function `map:new-merge` that returns the new map type.

**Comment by Reino17** [comment]
Above command with this new `map:new-merge()` function correctly returns `{"a":1,"b":2,"c":4}`.

Do I understand correctly that this is a temporary function until you fixed this in `map:merge()`?

**Comment by benibela** [comment]
>Do I understand correctly that this is a temporary function until you fixed this in map:merge()?

Yes. I will remove the old map:merge and rename map:new-merge to map:merge.

But the thing is that it returns a new map type. Every other function needs to be changed to accept such a new map type. And those are not all changed, like `request-combine(map:merge({}),"")` works, but `request-combine(map:merge({}),"")` does not.

And the speed difference comes afterwards:

>$ time xidel -se 'let $map := map:merge((1 to 100)!{.:.}) return ((1 to 10000000)! $map(50))[0]'
>real    0m12,850s
>$ time xidel -se 'let $map := map:new-merge((1 to 100)!{.:.}) return ((1 to 10000000)! $map(50))[0]'
>real    0m5,466s

**Comment by benibela** [comment]
with  https://github.com/benibela/internettools/commit/d9837b77816a3b32e643328b94bb47a35492a84e only the new maps will be used

**Comment by Reino17** [comment]
```
xidel -se 'map:merge(({"a":1,"b":2,"c":3},{"c":4}),{"duplicates":"use-last"})'
{
  "a": 1,
  "b": 2,
  "c": 4
}
```
Confirmed. Thank you.
