### ISSUE TITLE
Unable to add node with transform() function

### ISSUE THREAD

**Issue by tgoeg** [benibela/xidel#45]
Hello again.
I don't know whether I am misunderstanding xidel/xquery again or if this is a bug.

I need to manipulate a given XML, which works flawlessly for *existing* nodes:
```
xidel infile.xml --xml --xquery "transform(/, function(\$e) { \
                          if (name(\$e) = \"surveyls_title\" ) then <surveyls_title>$newsid: $stitle</surveyls_title>
                          else \$e })
```
However, I'd like to add a node before a given position, say before \<b>:
```
$ echo "<a><b></b></a>" | xidel --xml - --xquery "transform(/, function(\$e) { if (name(\$e) = \"b\") then (
<cannotinsertthistag/>
> \$e) else \$e })"
<?xml version="1.0" encoding="UTF-8"?>
**** Processing: stdin:/// ****
Error:
err:XPST0003: Unknown or unexpected operator: $ (possible missing comma , or closing parentheses)}] )
in: transform(/, function($e) { if (name($e) = "b") then (
<cannotinsertthistag/>
 [<- error occurs before here] $e) else $e })
```
I also tried building a variable before (with concat() or string-join()) to no avail (brackets get encoded as \&lt; and similar).
Is this possible at all and I am only doing it in the wrong way or does xidel not support this?

Please advise, thanks!

PS:
Btw: The online documentation at http://www.videlibri.de/xidel.html seems to be outdated.
The example given:
```
xidel --html your-file.html --xquery 'transform(/, function($e) { 
   $e / if (name() = "a") then 
           <a style="{join((@style, "font-weight: bold"), "; ")}">{@* except @style, node()}</a> 
        else .
})' > your-output-file.html
```
produces an error:
```
Error:
err:XPST0003: Reserved function name: if
in: transform(/, function($e) { 
   $e / if ( [<- error occurs before here] name() = "a") then 
           <a style="{join((@style, "font-weight: bold"), "; ")}">{@* except @style, node()}</a> 
        else .
})
```

**Comment by benibela** [comment]
>Unknown or unexpected operator: $ (_possible missing comma ,_

You need a comma between the element and $e.

Should I change the error message?

**Comment by tgoeg** [comment]
Well, sorry, the error message is as good as it gets, I guess this is my fault.
However, I didn't expect I'd need a comma somewhere.
Is this xidel specific?
Reading https://www.tutorialspoint.com/xquery/xquery_ifthenelse.htm , I did not see it anywhere.

Maybe an example for manipulating XML files (adding, removing, updating nodes) would help.
Also adding the double curlies needed in a JSON post (see issue #44) would help, I think.

I need to incorporate the changes that this solution allows me now (possibly next week), then I can provide an example for manipulating and importing LimeSurvey templates, if you like.

**Comment by Reino17** [comment]
> ```
> $ echo "<a><b></b></a>" | xidel --xml - --xquery "transform(/, function(\$e) { if (name(\$e) = \"b\") then (
> <cannotinsertthistag/>
> > \$e) else \$e })"
> ```

I assume you're on Unix, so use `--xquery 'function("string")'` instead of `--xquery "function('string')"`, which is for Windows users. This way you don't have to escape `$`, `"` and the end of a line either.

The following query is probably what you're lookin for.
```
$ echo "<a><b></b></a>" | xidel -s - --xml --xquery 'transform(/,function($x){if (name($x)="b") then (<cannotinsertthistag/>,$x) else $x})'
<?xml version="1.0" encoding="UTF-8"?>
<a><cannotinsertthistag/><b/></a>
```
Or prettified:
```
$ echo "<a><b></b></a>" | xidel -s - --xml --xquery '
  transform(
    /,
    function($x){
      if (name($x)="b") then
        (<cannotinsertthistag/>,$x)
      else
        $x
    }
  )
'
<?xml version="1.0" encoding="UTF-8"?>
<a><cannotinsertthistag/><b/></a>
```

Mind you that `(<cannotinsertthistag/>,$x)` is a sequence and thus requires parentheses surrounding it.

> `err:XPST0003: Reserved function name: if`

`-e 'if (...) then a else b'` works just fine, BUT with `-e '$x/(if (...) then a else b)'` the entire if-statement needs parentheses surrounding it.

> Maybe an example for manipulating XML files (adding, removing, updating nodes) would help.

Worth noting...  
_https://sourceforge.net/p/videlibri/mailman/videlibri-xidel/thread/3907afbb-b6da-0ce7-e04f-b34472f0c256%40benibela.de/#msg36904956_:
> > Am I right to say that Xidel is primarily an extraction tool and it was never your goal to create an editing tool?
> yes

**Comment by tgoeg** [comment]
Sorry for the simplified example. Yes, I am on linux and I have to use double quotes as I need to evaluate variables (shell-level ones, that is) in the call.

> -e 'if (...) then a else b' works just fine, BUT with -e '$x/(if (...) then a else b)' the entire if-statement needs parentheses surrounding it.

Then the documentation should have those parentheses added.

With the right documentation, transforming feels a little clumsy, but is possible. And yes,
>> Am I right to say that Xidel is primarily an extraction tool and it
>> was never your goal to create an editing tool?

>   yes

it feels so :-)

I still don't understand why I need a comma, as xquery does not specify it is necessary, so it seems to be xidel specific and should probably be noted in the docs as well. However, it's documented here at least now.
Thanks!

**Comment by benibela** [comment]
Internally the transform function does the same as [these functions](https://en.wikibooks.org/wiki/XQuery/Filtering_Nodes)

**Comment by tgoeg** [comment]
One more question:
I would have expected the following to insert `<inserted/>` before `<b></b>`
```
echo "<a><b></b></a>" | xidel -s - --xml --xquery 'transform(/,function($x){if (name($x)="b") then (<inserted/>,$x) else $x})'
<?xml version="1.0" encoding="UTF-8"?>
<a><inserted/><b/></a>
```
However, this is missing the `<b>`. On the one hand, name($x) matches "b" for `<b>` but on the other hand, when getting inserted, it is `</b>`. I don't quite understand this! (And would just like to add a node without altering the remaining structure of the document)

**Comment by benibela** [comment]
It is `<b/>` not `</b>`. `<b/>` is an abbreviation for `<b></b>`. After parsing `<b/>` and  `<b></b>` cannot be distinguished from each other

**Comment by tgoeg** [comment]
Ah.. my bad, sorry.
```
echo "<a><b>bcontent</b></a>" | xidel -s - --xml --xquery 'transform(/,function($x){if (name($x)="b") then (<inserted/>,$x) else $x})'

<a><inserted/><b>bcontent</b></a>
```
shows it is indeed working as expected. Thanks for helping out!
