### ISSUE TITLE
Bug: Xidel tries to parse input despite asking for $raw

### ISSUE THREAD

**Issue by Reino17** [benibela/xidel#46]
```
$ xidel -s - -e '$raw' <<EOF
[Title]

blah-blah-blah
EOF
Error:
err:FOJS0001: error at Title (tkIdentifier) in [Title]
[...]
```

With `-e '$json'` I get the same error-message (which is expected), but with `-e '$raw'` I was actually expecting just:
```
[Title]

blah-blah-blah
```

If this is indeed a bug, and if you don't want to change Xidel's default parsing behavior, would something like `--input-format=raw` be an option?

I found out about this when doing...
```
$ curl -s https://raw.githubusercontent.com/Reino17/xivid/master/xivid_notes.txt | sed -n 2948,3010p | xidel -s - -e '$json'
```
or locally `$ sed -n 2948,3010p xivid_notes.txt | xidel -s - -e '$json'`.  
This works just fine, but when I open the file or url directly with Xidel...
```
$ xidel -s https://raw.githubusercontent.com/Reino17/xivid/master/xivid_notes.txt -e 'x:lines($raw)[position() = 2948 to 3010]'
Error:
err:FOJS0001: error at Reeksen (tkIdentifier) in [Reeksen en positionering]
[...]
```

Only `file:read-text-lines()` / `unparsed-text-lines()` works so far:
```
$ xidel -s -e 'json(join(file:read-text-lines("xivid_notes.txt")[position() = 2948 to 3010]))'
$ xidel -s -e 'json(join(unparsed-text-lines("https://raw.githubusercontent.com/Reino17/xivid/master/xivid_notes.txt")[position() = 2948 to 3010]))'
```

**Comment by benibela** [comment]
Everything starting with `[` or `{` is treated as json..

`echo '{"a": 1}' | xidel - -e './a'` should return the 1

You can do `--input-format html`, the html parser is forgiving


>would something like --input-format=raw be an option?

Yes. Or could call it `--input-format=text` or `--input-format=unparsed`

**Comment by Reino17** [comment]
Alright. Thanks.

I'll leave it to you to close this issue.

**Comment by Reino17** [comment]
`--input-format=text` works. Thanks.  
You forgot to update https://github.com/benibela/xidel/blob/master/xidelbase.pas#L3521 however.

**Comment by Reino17** [comment]
```
$ xidel --version
Xidel 0.9.9
(20210720.7961.2e0374a546a6)

$ printf [test] | xidel -s --input-format=text -e '$raw'
Error:
err:FOJS0001: error at test (tkIdentifier) in [test]

$ printf [test] | xidel -s --input-format=text - -e '$raw'
[test]
```
Ever since https://github.com/benibela/xidel/commit/1320f7a7b4f973482e8870e708f2ee3ba15e3082 it's not necessary anymore to enter the stdin dash `-`, but here it apparently still is. Is this intended, or could this be considered a bug?
```
$ printf [test] | xidel -s --input-format=text -e 'read()'
Error:
err:FOJS0001: error at test (tkIdentifier) in [test]
```
Even `read()`, which at the moment doesn't work for stdin anymore, tries to parse the input.

**Comment by Reino17** [comment]
```
$ printf ''\''çömmít'\'' "mêssågè"' | \
  xidel -s \
  -d '{serialize({"text":read()},{"method":"json","encoding":"us-ascii"})}' \
  "https://api.github.com/markdown" \
  -e '$raw'
<p>'çömmít' "mêssågè"</p>

$ printf '[category]: '\''çömmít'\'' "mêssågè"' | \
  xidel -s --input-format=text \
  -d '{serialize({"text":read()},{"method":"json","encoding":"us-ascii"})}' \
  "https://api.github.com/markdown" \
  -e '$raw'
```
`--input-format=text` appears to have no effect on `-d` and/or `read()`.

**Comment by benibela** [comment]
>--input-format=text appears to have no effect on -d and/or read().

indeed

**Comment by Reino17** [comment]
I removed that post, because it was an error on my end. The server doesn't accept strings starting with a `[` anyway. This did work though:
```
$ printf '[category]: '\''çömmít'\'' "mêssågè"' | \
  xidel -s --input-format=text \
  -d '{
    serialize(
      {"text":read()},
      {
        "method":"json",
        "encoding":"us-ascii",
        "use-character-maps":{"[":"(","]":")"}
      }
    )
  }' \
  "https://api.github.com/markdown" \
  -e '$raw'
<p>(category): 'çömmít' "mêssågè"</p>
```

**Comment by Reino17** [comment]
I think you missed my question about `$ printf [test] | xidel -s --input-format=text -e '$raw'` above. Could you answer that still?

**Comment by benibela** [comment]
> I think you missed my question about `$ printf [test] | xidel -s --input-format=text -e '$raw'` above. Could you answer that still?

It does not work without -, since it ignores the input-format. Perhaps I will change it to not ignore it
