### ISSUE TITLE
xidel skips the commented "<!-- abc -->" html

### ISSUE THREAD

**Issue by MegaCron** [benibela/xidel#47]
Hi all.

xidel skips the commented data  "" in html. I have to use sed and remove the escape characters "" to parse the data in html via xidel. Is it possible to do this without using sed ?

**Comment by benibela** [comment]
It is not skipped here:

```
$ xidel  '<html><!-- abc --></html>' --html -e /
**** Processing: data:,<html><!-- abc --></html> ****
<!DOCTYPE html>
<html><!-- abc --><head></head><body></body></html>

```

**Comment by MegaCron** [comment]
>It is not skipped here:

ОК :) How do I get commented data ?

If there are escaped lines in html, I get an empty string

`xidel '<div id="abc-data"><!-- {"def":{"ghi":"jkl"}} --></div>' -se "//div[@id='abc-data']"`
`
`

And if there are no escaped lines in html, I get data

`xidel '<div id="abc-data">{"def":{"ghi":"jkl"}}</div>' -se "//div[@id='abc-data']"`
`{"def":{"ghi":"jkl"}}`

**Comment by thedward** [comment]
Try

```
xidel --output-format=xml '<div id="abc-data"><!-- {"def":{"ghi":"jkl"}} --></div>' -se "//div[@id='abc-data']"
```

**Comment by Reino17** [comment]
```
xidel '<div id="abc-data"><!-- {"def":{"ghi":"jkl"}} --></div>' -se '//div[@id="abc-data"]/comment()'
 {"def":{"ghi":"jkl"}}

xidel '<div id="abc-data"><!-- {"def":{"ghi":"jkl"}} --></div>' -se '//div[@id="abc-data"]/json(comment())'
{
  "def": {
    "ghi": "jkl"
  }
}
```

> `-se "//div[@id='abc-data']"`

Please mind your quoting. This is for Windows.  
`-se '//div[@id="abc-data"]'` is for Unix.

**Comment by MegaCron** [comment]
As thedward said:

> Try
> 
> ```
> xidel --output-format=xml '<div id="abc-data"></div>' -se "//div[@id='abc-data']"
> ```

This example returns only colorized xml :\

As Reino17 said:

> `xidel '<div id="abc-data"><!-- {"def":{"ghi":"jkl"}} --></div>' -se '//div[@id="abc-data"]/comment()'`
>  `{"def":{"ghi":"jkl"}}`
> 
> `xidel '<div id="abc-data"><!-- {"def":{"ghi":"jkl"}} --></div>' -se '//div[@id="abc-data"]/json(comment())'`

Thanks. It works. This is the solution that I needed :)

> `-se '//div[@id="abc-data"]'` is for Unix.

Under unix, expressions with single and double quotes give the same result + double quotes allow the use of "$" variables :)

**Comment by Reino17** [comment]
Ok. Depends on the shell then I guess.  
System variables can also be called when using single quotes:
```
$ var=bar

$ xidel -se 'concat("foo","'$var'")'
foobar

$ xidel -se 'let $var:="foo" return $var||"'$var'"'
foobar
```

**Comment by MegaCron** [comment]
>Ok. Depends on the shell then I guess.
>System variables can also be called when using single quotes:

Thanks. This works for me. I close this issue :)

**Comment by Reino17** [comment]
For completeness sake, a follow-up to my previous post:

### Unix ###
Using (the Bash default) single quotes:

```
var=bar

xidel -se 'concat("foo","'$var'")'
xidel -se 'concat("foo",environment-variable("var"))'
xidel -se 'let $var:="foo" return $var||"'$var'"'
```

Using double quotes:

```
var=bar

xidel -se "concat(\"foo\",\"$var\")"
xidel -se "concat(\"foo\",environment-variable(\"var\"))"
xidel -se "let \$var:=\"foo\" return \$var||\"$var\""
```
Output in all cases: `foobar`.

### Windows ###

Using (the CMD default) double quotes:

```
SET var=bar

xidel -se "concat('foo','%var%')"
xidel -se "concat('foo',environment-variable('var'))"
xidel -se "let $var:='foo' return $var||'%var%'"
```

Using single quotes:

```
SET var=bar

xidel -se 'concat("foo","%var%")'
xidel -se 'concat("foo",environment-variable("var"))'
xidel -se 'let $var:="foo" return $var^|^|"%var%"'
```
Output in all cases: `foobar`.
