### ISSUE TITLE
android app build error: Failed to notify project evaluation listener

### ISSUE THREAD

**Issue by colourful-land** [benibela/xidel#53]
(my intention is to use xidel in an Android app, been evaluating it for a few weeks thinking it's the tool I'd go with)

This build error can be reproduced with gradle 5.4 or 6.4.

1. Prepare

delete the parts in build.gradle that involves keys
````
diff --git a/android/app/build.gradle b/android/app/build.gradle
index fdc91c1..ea47fc4 100644
--- a/android/app/build.gradle
+++ b/android/app/build.gradle
@@ -28,10 +28,6 @@ android
   
   signingConfigs {
     release {
-      storeFile file('/home/benito/hg/information/android.keystore')
-      storePassword ANDROID_STORE_PASSWORD
-      keyAlias 'videlibri'
-      keyPassword ANDROID_KEY_PASSWORD
     }
   }
   buildTypes {
````

2. Make missing directories

````
$ mkdir -p android/app/src/debug/resources
$ mkdir -p android/app/src/main/resources
$ mkdir android/app/libs
````

3. build 
stacktrace here:

[stacktrace.txt](https://github.com/benibela/xidel/files/4784777/stacktrace.txt)

````
$ ANDROID_HOME=/opt/android/ gradle build 
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 939ms
````

**Comment by benibela** [comment]
I completely forgot about the xidel android app. 

I think I need to delete that android directory and start from scratch. I tried to make a Xidel GUI using the [Lazarus CustomDrawn Interface](https://wiki.lazarus.freepascal.org/Custom_Drawn_Interface/Android). In theory, it is perfect, you write the GUI code once and the same GUI can run on Windows, Mac, Linux, and Android. In practice, it often crashed and there was almost no maintenance in the last 7 years

In my VideLibri project, I have the Android GUI in Kotlin, compile my Internet Tools to a .so library, and then load that library to run XQuery.

**Comment by benibela** [comment]
I have removed this directory
