### ISSUE TITLE
x:request({"user-agent":[...]}) doesn't work

### ISSUE THREAD

**Issue by Reino17** [benibela/xidel#58]
```
xidel-0.9.9-7622-1650cd0-openssl-win32.exe -s --method=HEAD https://ipinfo.io -e "$headers[3]"
Content-Type: text/html; charset=utf-8

xidel-0.9.9-7622-1650cd0-openssl-win32.exe -s --user-agent=curl --method=HEAD https://ipinfo.io -e "$headers[3]"
Content-Type: application/json; charset=utf-8

xidel-0.9.9-7622-1650cd0-openssl-win32.exe -se "x:request({'user-agent':'curl','method':'HEAD','url':'https://ipinfo.io'})/headers[3]"
Content-Type: text/html; charset=utf-8
```
The user-agent is obligatory for https://ipinfo.io to return its JSON.  
`--user-agent` works, but it seems `x:request({'user-agent':[...]})` has never worked. Every previous `xidel` version shows the same thing.

https://github.com/benibela/xidel/issues/55#issuecomment-723493828:
> _The proxy and user agent are set once when xidel is started, and afterwards nothing can change them_

Why? With a scenario like...
```
xidel -se "
  let $src1:=x:request({'user-agent':[...],'url':<url1>}),
      $src2:=x:request({'url':<url2>}),
      $src3:=x:request({'user-agent':[...],'url':<url3>})
  return
  [...]
"
```
...that's a real limitation, if you ask me.

**Comment by benibela** [comment]
implemented in
https://github.com/benibela/internettools/commit/8b3bbdee34b970fcab0e7fb35935bf800fcb285e
https://github.com/benibela/internettools/commit/445d3cff98f3eb2de862be57ac0e507e1f50c3c5
https://github.com/benibela/xidel/commit/a2b6eeabbe6dcad5824f7e0b72f6fb154b4508a0

**Comment by Reino17** [comment]
No new development builds yet, so I tried to build `xidel` myself, but trying to build with FPC 3.0.4 I'm getting...
```
Compiling .\components\pascal\data\xquery_module_file.pas
Compiling .\components\pascal\data\xquery.internals.lclexcerpt.pas
Compiling .\components\pascal\data\xquery_module_math.pas
Compiling .\components\pascal\data\xquery_module_uca_icu.pas
Compiling .\components\pascal\internet\internetaccess_inflater_paszlib.pas
Compiling .\components\pascal\system\rcmdline.pas
rcmdline.pas(449,15) Warning: Local variable "res" of a managed type does not seem to be initialized
rcmdline.pas(759,88) Warning: Local variable "value" of a managed type does not seem to be initialized
rcmdline.pas(601,3) Warning: Function result variable does not seem to initialized
rcmdline.pas(816,26) Error: identifier idents no member "Options"
rcmdline.pas(818,26) Error: identifier idents no member "UseLocale"
rcmdline.pas(1458) Fatal: There were 2 errors compiling module, stopping
Fatal: Compilation aborted
Error: C:\FPC-3.0.4\bin\i386-win32\ppc386.exe returned an error exitcode
```

**Comment by benibela** [comment]
just [remove those lines](https://github.com/benibela/rcmdline/commit/618dbee077d2d1d3deb98d1a0612af968e55e77d)

> but trying to build with FPC 3.0.4 I'm getting...

that is getting too old to support it much longer

**Comment by Reino17** [comment]
Updated to FPC 3.2.2. All fine now.

Fix confirmed. Thanks!
