### ISSUE TITLE
[Feature request] short option flags for `--printed-node-format` and `--ignore-namespaces`

### ISSUE THREAD

**Issue by goekce** [benibela/xidel#59]
I use `xidel` in a course where we parse XML files. We used `xmllint` for that, but `xmllint` does not support parsing without setting the namespaces, and I am grateful that I found `xidel`!

As my students are used to `xmllint` output, I have to use `--printed-node-format=xml` and `--ignore-namespaces` to get a similar output. `xidel` outputs the content of a node immediately without having to provide `text()`, which is convenient.

Example:

```
xidel https://www.uniprot.org/uniprot/P21817.xml \
  --printed-node-format=xml \
  --ignore-namespaces \
  -se '//protein'
```
```xml
<protein>
<recommendedName>
<fullName>Ryanodine receptor 1</fullName>
<shortName>RYR-1</shortName>
...
</protein>
```

It takes time for the users to write these long options. Is it possible to add shorter option flags for `--printed-node-format` and `--ignore-namespaces`? Or did I miss any alternative options?

**Comment by benibela** [comment]
There is `--xml` to set input and output format. Or use  `-se 'serialize(//protein)'`

There is a nothing shorter for --ignore-namespaces. You could set it permanently though `export XIDEL_OPTIONS=--ignore-namespaces`. It is a hardly used option (I had even forgotten that it was there).

**Comment by goekce** [comment]
`--xml` is a convenient alternative with a minor inconvenience for my case (see below).

`-se 'serialize(//protein)'` sometimes messes up the output, and does not use coloring on my terminal:

```
$ xidel https://www.uniprot.org/uniprot/P21817.xml -se 'serialize(//fullname)'
<fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Ryanodine receptor 1</fullName><fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Skeletal muscle calcium release channel</fullName><fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Skeletal muscle ryanodine receptor</fullName><fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Skeletal muscle-type ryanodine receptor</fullName><fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Type 1 ryanodine receptor</fullName>
```

I use `--ignore-namespaces` for instructional and experimenting purposes to declutter the output, e.g.:
```
$ xidel https://www.uniprot.org/uniprot/P21817.xml --xml -se '//fullname'
<?xml version="1.0" encoding="UTF-8"?>
<xml>
<fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Ryanodine receptor 1</fullName>
<fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Skeletal muscle calcium release channel</fullName>
<fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Skeletal muscle ryanodine receptor</fullName>
<fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Skeletal muscle-type ryanodine receptor</fullName>
<fullName xmlns="http://uniprot.org/uniprot" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">Type 1 ryanodine receptor</fullName>
</xml>
```
 
with `--ignore-namespaces`: 
```
$ xidel https://www.uniprot.org/uniprot/P21817.xml --xml -se '//fullname' --ignore-namespaces
<?xml version="1.0" encoding="UTF-8"?>
<xml>
<fullName>Ryanodine receptor 1</fullName>
<fullName>Skeletal muscle calcium release channel</fullName>
<fullName>Skeletal muscle ryanodine receptor</fullName>
<fullName>Skeletal muscle-type ryanodine receptor</fullName>
<fullName>Type 1 ryanodine receptor</fullName>
</xml>
```

For experimenting on the shell, I still find `--printed-node-format=xml` better than `--xml`, though, because `xml` nodes are completely gone:
```
$ xidel chebi_27732_P21817.xml --printed-node-format=xml -se '//fullname' --ignore-namespaces
<fullName>Ryanodine receptor 1</fullName>
<fullName>Skeletal muscle calcium release channel</fullName>
<fullName>Skeletal muscle ryanodine receptor</fullName>
<fullName>Skeletal muscle-type ryanodine receptor</fullName>
<fullName>Type 1 ryanodine receptor</fullName>
```

My cases may be not very common, I can understand that! Nevertheless `XIDEL_OPTIONS` is also a good way to avoid the long options in subsequent iterations of the command. I hope that `--ignore-namespaces` and `--printed-node-format` stay as options in future. Thanks Benito!
