### ISSUE TITLE
License

### ISSUE THREAD

**Issue by dacbarbos** [benibela/xidel#6]
According SF.net project's page, this code is released under GPLv2, yet a "LICENSE.{md|txt}" file is missing. Please add (choosealicense.com).

**Comment by benibela** [comment]
Is the header not sufficient? 
https://github.com/benibela/xidel/blob/master/xidelbase.pas

**Comment by dacbarbos** [comment]
See [this](https://github.com/blog/1964-open-source-license-usage-on-github-com).

**Comment by benibela** [comment]
added COPYING: https://github.com/benibela/xidel/commit/ec933adbffc99563cbd44aa38984b91ddca01a6c
