### ISSUE TITLE
https no longer works

### ISSUE THREAD

**Issue by ralyodio** [benibela/xidel#68]
```
$ xidel -s 'https://www.marketwatch.com/investing/stock/AMD' -e '.'
Error:
Internet Error: -3 HTTPS connection failed after connecting to server. Some possible causes: handshake failure, mismatched HTTPS version/ciphers, invalid certificate
OpenSSL-Error: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
when talking to: https://www.marketwatch.com/investing/stock/AMD
```

**Comment by benibela** [comment]
It did not use to validate certificates properly. But now it does the validation correctly, but needs CA root certificates to that

Where are the CA certificates on your system? 

Try it with the  certificates from https://curl.haxx.se/ca/cacert.pem (put them where xidel can find them or use `--ca-certificate=cacert.pem`)

**Comment by chovy** [comment]
this seems like unnecessary work. why would curl work but not xidel?

**Comment by benibela** [comment]
That depends on how it was installed. 

With the -v option curl shows where it is gets the CA certificates from.

On my system:

```
$ curl -v https://marketwatch.com
*   Trying 52.222.177.23:443...
* TCP_NODELAY set
* Connected to marketwatch.com (52.222.177.23) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs

```

If you have them in `/etc/ssl/`, too, Xidel should find them, too

**Comment by chovy** [comment]
CAPath is empty for me.

**Comment by benibela** [comment]
And CAFile?

**Comment by chovy** [comment]
same as yours.

**Comment by benibela** [comment]
Well, then it should work

Have you tried the cacert.pem ? Or the  `--no-check-certificate` option

What is your OpenSSL version?

**Comment by benibela** [comment]
no feedback
