### ISSUE TITLE
[Request] Strip excessive whitespace when exporting JSON with --output-format={bash|cmd}

### ISSUE THREAD

**Issue by Reino17** [benibela/xidel#71]
Linux:
```
$ xidel -s '{"a":1,"b":"x y z","c":null}' -e '$json' --output-format=bash
result='{"a": 1, "b": "x y z", "c": null}'
```
Windows:
```
xidel -s "{'a':1,'b':'x y z','c':null}" -e "$json" --output-format=cmd
SET result={^"a^": 1^, ^"b^": ^"x y z^"^, ^"c^": null}
```
It's almost as if the JSON input is serialized with `serialize-json()` as opposed to `serialize()`:
```
xidel -s '{"a":1,"b":"x y z","c":null}' -e 'serialize-json($json)'
{"a": 1, "b": "x y z", "c": null}

xidel -s '{"a":1,"b":"x y z","c":null}' -e 'serialize($json,{"method":"json"})'
{"a":1,"b":"x y z","c":null}
```
*(isn't `serialize-json()` unnecessary/superfluous now?)*

Probably less a concern on Linux, but Windows `cmd` its commandline buffer is only 8KB. So `cmd` variables can only hold a max of 8192 characters.  
With that in mind can you please strip excessive whitespace, like `serialize()` does, when exporting JSON with `--output-format={bash|cmd}`, Benito?

**Comment by Reino17** [comment]
One month later. Can you at least share your opinion on the matter?

**Comment by benibela** [comment]
>It's almost as if the JSON input is serialized with serialize-json() as opposed to serialize():

yes

>One month later.

Already? It feels like yesterday

>Can you at least share your opinion on the matter?

it is not so easy to change

**Comment by Reino17** [comment]
Very nice. Thank you very much!
