### ISSUE TITLE
xidel for window making requests through the default Internet Explorer proxy ?

### ISSUE THREAD

**Issue by Baltazar500** [benibela/xidel#73]
xidel for window making requests through the default Internet Explorer proxy ? 

I use fake proxy (127.0.0.1:22222) in Internet Explore settings to block hidden windows requests, which is why xidel does not return data when proxy is enabled. 

I have to use the `--proxy=""` switch when fake proxy is enabled in the settings :(

**Comment by benibela** [comment]
Yes

I added that feature this month: https://github.com/benibela/xidel/commit/baff543d3ba546731615485b0c4ab5c23b7f2c8d

**Comment by Baltazar500** [comment]
>Yes

As I expected. IMHO, this feature is not obvious and complicates work with xidel under windows :/

**Comment by benibela** [comment]
But it makes sense. The default proxy is the default proxy

And disabling it with `--proxy=""` is more intuitive than enabling with `--proxy=default` or something

And all the other Internet Explorer settings (TLS especially) affect Xidel as well

**Comment by Baltazar500** [comment]
ОК
