### ISSUE TITLE
post request not working

### ISSUE THREAD

**Issue by Fuzzyma** [benibela/xidel#8]
I need to send a post request. I try so doing:

``` sh
xidel "http://annuaire.cncc.fr/index.php?page=liste&p=1" --method POST -d "recherche=1&nature_fiche=toutes&nom_societe=&cp_ville=&crcc=0&x=34&y=18" -e '//html'
```

That doenst work. Also when I split up the patameters:

``` sh
xidel "http://annuaire.cncc.fr/index.php" --method POST -d "recherche=1" -d "nature_fiche=toutes" -d "nom_societe=" -d "cp_ville=" -d "crcc=0" -d "x=34" -d "y=18" -e '//html'
```

it always prints `**** Retrieving (GET): http://annuaire.cncc.fr/index.php ****`.
How do I convince xidel to do a post request instead?

**Comment by benibela** [comment]
You need to place the url after the data.


    xidel --method .. -d .. http:/... -e ...

You can think of it like a pipe. Set the data, make the http request, process it. If the url comes first, it makes the http request, sets the data afterwards, but there is nothing to send them to.

Only for some arguments there is a check, if they are at  position where they will be ignored, to automatically reorder them (that is why xidel -e ... http://... works)

**Comment by Fuzzyma** [comment]
mh ok its doing post requests now. However - this works:

```sh
curl 'http://annuaire.cncc.fr/index.php?page=liste' --data 'recherche=1&nature_fiche=toutes&nom_societe=&cp_ville=&crcc=0&x=34&y=18'
```

but this not:

```sh
xidel --method="post" -d "recherche=1&nature_fiche=toutes&nom_societe=&cp_ville=&crcc=0&x=34&y=18" "http://annuaire.cncc.fr/index.php?page=liste&p=1" -e '//html'
```

**Comment by benibela** [comment]
What is the expected result?

**Comment by Fuzzyma** [comment]
When it fails, I get back a website saying that no results where found (in france). I expect to get the table with the results instead

**Comment by benibela** [comment]
It works for me. Which OS/version are you using?

**Comment by Fuzzyma** [comment]
Windows 7 64 bit (Xidel 0.9.4)

**Comment by benibela** [comment]
Then Windows sends happily any method string, while it is sanitized on linux.

It is --method POST, not --method post. Or just leave it

**Comment by Fuzzyma** [comment]
I dont believe I missed that. I already saw this mistake earlier in all my tests. Thank you very much!
