### ISSUE TITLE
Doubt: what is the meaning of the .pem file?

### ISSUE THREAD

**Issue by msmafra** [benibela/xidel#84]
Doubt: what is the meaning of the .pem file?
I've been using xidel 0.9.8, but I saw you recommended 0.9.9, but I haven't noticed before the .pem file to install.
Would it work, if needed, with xidel in ~/.local/bin (prefix I use) and it inside ~/.loca./share/xidel ?

**Comment by benibela** [comment]
It is a collection of CA certificates for OpenSSL. 

Here is where it searches for them:

https://github.com/benibela/internettools/blob/8aea1189ad60d2717231df80fc64c0be8491d924/internet/internetaccess.pas#L842-L907

https://github.com/benibela/xidel/blob/1a65048dbd0b20eaa3db27eab5bea2ee3dd9013a/xidelbase.pas#L3847-L3850

It does not search in `~`, but in the current path

On Linux, it probably does not need this file at all, when it finds some already globally installed CA certificates

**Comment by msmafra** [comment]
Hello there.
Thank you very much
