### ISSUE TITLE
Empty output when using full xpath for a html file

### ISSUE THREAD

**Issue by Baltazar500** [benibela/xidel#88]
Hi.

I am getting empty output when using the full xpath for a html file. 

Expression : 

```

 xidel -se '/html/body/center/table/tr/td' './test.html'

```

Example :

```

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN" "">
<html>
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <center>
      <table border="1" cellpadding="5">
        <tr>
          <td>123</td>
        </tr>
        <tr>
          <td>456</td>
        </tr>
      </table>
    </center>
  </body>
</html>

```

With all this, when using the pipe and processing stdout of the same file, everything works

```

cat ./test.html|xidel -se '/html/body/center/table/tr/td'
123
456

```

What is the problem ?

**Comment by benibela** [comment]
It is turning the file into:

```

<html>
  <head>
    <meta charset="utf-8"/>
  </head>
  <body>
    <center>
      <table border="1" cellpadding="5">
        <tbody><tr>
          <td>123</td>
        </tr>
        <tr>
          <td>456</td>
        </tr>
      </tbody></table>
    </center>
  



</body></html>

```

So you need  `xidel -se '/html/body/center/table/tbody/tr/td' './test.html'`

That is how it is supposed to be in HTML5. Although Xidel does not have a HTML5 parser. Looks like I started implementing parts of HTML5 and then forgot about them...

**Comment by Baltazar500** [comment]
>If you rename it to test.xml, it will also use the XML parser

Yes, it works. And it worked too

>xidel --input-format=xml -se '/html/body/center/table/tr/td' './test.html'
>123
>456

**Comment by Baltazar500** [comment]
Any changes expected ? Should I close this issue or will you close it ?
