### ISSUE TITLE
xidel linux32 from 20220424 does not work. libc.so.6: version `GLIBC_2.34' not found

### ISSUE THREAD

**Issue by Baltazar500** [benibela/xidel#91]
The latest revision of xidel under 'Antix' (i386/i586) does not start. I get an error :

>/bin/xidel-0.9.9.20220424.8389.2d2ee7befb8a.linux32: /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /bin/xidel-0.9.9.20220424.8389.2d2ee7befb8a.linux32)

Revision 20220131 works without problems

**Comment by benibela** [comment]
Looks like GLIBC_2.34 is incompatible to older GLIBCs:

https://forum.lazarus.freepascal.org/index.php/topic,58888.msg438860.html

https://gitlab.com/freepascal.org/fpc/projects/-/issues/3#note_892374986

Guess I need to build multiple Xidel versions for different glibcs. Not sure if i can do that on my computer after the newest things are installed

**Comment by benibela** [comment]
Now there are builds with the old FreePascal and old Ubuntu: https://nightly.link/benibela/xidel/workflows/main/master
