### ISSUE TITLE
fn:matches (version 0.9.9 FPC3.2+) crashes on macOS

### ISSUE THREAD

**Issue by Fravadona** [benibela/xidel#93]
Given the followings XML:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<a>X</a>
```

Here's what I get when I run `xidel --xpath 'matches( /a/text(), "a|b" )' input.xml`:

* nightly binary for **macOS**

###### Xidel 0.9.9 (20220605.git87483a690c50ef2a60fbebf83055ce46f9c2b6ac) FPC3.2.2 x86_64-Darwin

```text
An unhandled exception occurred at $0000000101E13F13:
EAccessViolation: Access violation
  $0000000101E13F13
  $0000000101CC4777
```

* compiled from source with **FPC 3.2.2** on **macOS**

###### Xidel 0.9.9 (20220424.8389.2d2ee7befb8a) FPC3.2.2 x86_64-Darwin

```text
An unhandled exception occurred at $000000010357B303:
EAccessViolation: Access violation
  $000000010357B303
  $00000001033E87C7
```

* compiled from source with **FPC 3.2.2** on **Linux**

###### Xidel 0.9.9 (20220424.8389.2d2ee7befb8a) FPC3.2.2 x86_64-Linux
```sh
false
```

* compiled from source with **FPC 3.0.4a** on **macOS**

###### Xidel 0.9.9 (20220424.8389.2d2ee7befb8a) FPC3.0.4a x86_64-Darwin
```sh
false
```

I attached the build logs of Xidel using FPC 3.2.2 on Linux and macOS so that you can see the several new warnings that appear on macOS.

[xidel_build_linux.log](https://github.com/benibela/xidel/files/9255518/xidel_build_linux.log)
[xidel_build_macos.log](https://github.com/benibela/xidel/files/9255519/xidel_build_macos.log)

**Comment by benibela** [comment]
What does the debug version say? Or compiled with `-g -gl`? Or when it is run through gdb (after the error use commands `disassemble` and `backtrace` to get more information)? 

I do not have a Mac to investigate this

**Comment by Fravadona** [comment]
I didn't find the debug version, compiling Xidel with `-g -gl` doesn't yield anything more than the previous crash message, and getting `gdb` to work on macOS is so convoluted... But here's the log:

[gdb.log](https://github.com/benibela/xidel/files/9267435/gdb.log)

**Comment by benibela** [comment]
Looks like that issue I encountered last month when updating fpc: https://github.com/BeRo1985/flre/issues/85

Try compiling it with the [patched flre](https://github.com/benibela/flre/commit/3e926d45d4352f1b7c7cd411ccd625df117dad5c)

**Comment by Fravadona** [comment]
Hi,

The patch fixes the macOS issue

Thank you
